# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
